# Site settings
title: Open Water Logger
description: Open Water Logger website
baseurl: ""
url: "https://openwaterlogger.org"

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
# exclude:
#   - package.json
#   - README.md
#   - CNAME
#   - assets/sass-

# collections:
#   docs:
#     output: true

# DOCS


# markdown docs
# markdown: kramdown
# kramdown:
#   auto_ids: true

# sidebar layout
# sidebar:
#   - title: Getting Started
#     items:
#       - title: Introduction
#         url: index.html
#       - title: Install / Setup
#         url: install.html
#       - title: Configure
#         url: configure.html
#       - title: Observe
#         url: observe.html
#       - title: Customize Snapshot Inputs
#         url: customize-snapshot.html
#       - title: Connect External Sensors
#         url: connect-external.html
#       - title: Access Data
#         url: access-data.html
#   - title: Topics
#     items:
#       - title: Units
#         url: units.html
#       - title: External Sensors
#         url: external-sensors.html
#       - title: Data Model
#         url: data-model.html
#       - title: Sensor Bursts
#         url: sensor-burst.html
#   - title: References
#     items:
#       - title: API Reference
#         url: api.html
#   - title: Support
#     items:
#       - title: Data Collection & Sharing
#         url: privacy.html
#       - title: Changelog
#         url: changelog.html

# primary navigation
# nav:
#   - title: Data Map
#     mobile_title: Map
#     permalink:
#     url: https://map.weathercitizen.org/
#   - title: How it Works
#     mobile_title: How it Works
#     permalink: how-it-works
#     url: /how-it-works.html
#   - title: Support
#     mobile_title: Support
#     children: 
#       - title: Documentation
#         mobile_title: Docs
#         permalink: docs
#         url: /docs
#       - title: Forum
#         mobile_title: Forum
#         permalink: forum
#         url: https://forum.weathercitizen.org/
#       - title: Contact
#         mobile_title: Contact
#         permalink: contact.html
#         url: /contact.html
#   - title: Get the App
#     mobile_title: Download
#     permalink:  download-app
#     url: /download-app.html

# footer navigation
# footer_nav:
#   - title: Contact
#     url: /contact.html
#   - title: Documentation
#     url: /docs
#   - title: Legal
#     url: /legal.html

#contact information
# contact_email: info@weathercitizen.org
